### ISSUE TITLE
how to get 3D structure of protein?

### ISSUE THREAD

**Issue by autodataming** [Urinx/alphafold_pytorch#11]
how to get 3D structure of protein?
the output is distogram.

https://github.com/deepmind/deepmind-research/issues/43

**Comment by lumramirezch** [comment]
I guess that you can use the distogram in `.rr` and retrieve the 3D with [GDFuzz3D](http://genesilico.pl/gdserver/GDFuzz3D/method_overview.html)

**Comment by nicolasfredesfranco** [comment]
GDFuzz3D works!

**Comment by shahik** [comment]
I tried:  !/bin/bash ./alphafold.sh
!python alphafold.py -i test_data/T1019s2.pkl -o T1019s2_out -t D -r 0

but no .rr file how can I get that ?
Greetings!
