### ISSUE TITLE
README.md typo in command

### ISSUE THREAD

**Issue by alprnbg** [Urinx/alphafold_pytorch#2]
I guess,
`python alphafold.py -i test_data/T1019s2.pkl -o T1019s2_out -t D -t 0`

should be
`python alphafold.py -i test_data/T1019s2.pkl -o T1019s2_out -t D -r 0`

**Comment by pentadotddot** [comment]
Hi! Could you make this whole thing work with like a sequence which is not included already in the casp dataset?
I am trying to make MSA with feature.sh from sars-cov2 sequences, but I could not manage to create tfrec files to input the alphafold machinery... :(

**Comment by Urinx** [comment]
@pentadotddot you can open a new issue to discuss, it's not related to this.
